apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-app
  template:
    metadata:
      labels:
        app: booking-app
    spec:
      containers:
      - name: booking-container
        image: 23mis0383/booking-app:latest
        ports:
        - containerPort: 5000
