apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  selector:
    app: booking-app # This MUST match the labels in your deployment.yaml
  ports:
    - protocol: TCP
      port: 80         # The port accessible from outside the cluster
      targetPort: 5000 # The port your Flask app is listening on inside the container
  type: LoadBalancer
